# Project information
site_name: SI Documentation
site_description: "Technical documentation for Lesotho's SI Health Systems"
site_author: "Ministry of Health"
site_url: ""

# Copyright
copyright: "Copyright &copy; 2020 Ministry of Health - Lesotho"

# Theme
theme:
    name: "material"
    palette:
      primary: "#2d3479"
      accent: "indigo"
    language: "en"
    features:
      - tabs
    font:
      text: "Roboto"
      code: "Roboto Mono"


# Nagivation
nav:
  - Overview:
    - 'index.md'
  - DHIS2:
    - 'dhis2/intro.md'
  - eRegister:
    - 'ereg/intro.md'

markdown_extensions:
- admonition
  - codehilite:
      guess_lang: false
  - toc:
      toc_depth : "1-1"
  - footnotes

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/eRegister